#!/bin/bash

# Default screen resolution
resolution='1600x900'

# Attempt to detect the resolution
if [[ $(xdpyinfo | grep dimensions) =~ ([[:digit:]]+x[[:digit:]]+) ]]; then

	resolution=${BASH_REMATCH[1]}
fi

# Clear screen and start capture
clear
ffmpeg -y -f x11grab -video_size $resolution -i :0.0 -filter:v scale=800:-1 -r 8 keys.gif >& /dev/null &

# Store process ID so we can kill it later
pid=$!

# Start keystroke playback
scriptreplay -d 1.5 keys.timing keys

# Stop screen capture
kill $pid

clear
echo Screencast - render complete
